# Generated by Django 2.0.4 on 2018-04-11 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=models.CharField(max_length=200, verbose_name='名称'),
        ),
    ]
